### numpy Add function

In [1]:
import numpy as np
a=np.array([10,20,100,200,500])
b=np.array([3,4,5,6,7])
np.add(a,b)

array([ 13,  24, 105, 206, 507])

### Numpy Add operator

In [3]:
import numpy as np
a=np.array([10,20,100,200,500])
b=np.array([3,4,5,6,7])
print(a+b)

[ 13  24 105 206 507]


### 2 D Array

In [6]:
import numpy as np
var21=np.array([[1,2,3,4,5],[1,2,3,4,5]])
var22=np.array([[1,2,3,4,5],[1,2,3,4,5]])
varadd=var21+var22
print(var21)
print(varadd)               

[[1 2 3 4 5]
 [1 2 3 4 5]]
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


### 3D Array

In [1]:
import numpy as np
a=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
b=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
c=a+b
print(c)

[[[2 4 6 8]
  [2 4 6 8]
  [2 4 6 8]]]


### Numpy Sum Function

In [2]:
a=np.array([2,4,3],float)
a.sum()

9.0

### Numpy Subtract function

In [3]:
import numpy as np
a=np.array([10,20,100,200,500])
b=np.array([2,8,5,4,6])
np.subtract(a,b)

array([  8,  12,  95, 196, 494])

### Numpy Subtract Operator

In [4]:
import numpy as np
a=np.array([10,20,100,200,500])
b=np.array([2,8,5,4,6])
print(a-b)

[  8  12  95 196 494]


### 2D:

In [5]:
import numpy as np
var3=np.array([4,5,6,7])
var4=np.array([1,2,3,4])
varsub=np.subtract(var3,var4)
print(varsub)

[3 3 3 3]


### 3D:

In [7]:
import numpy as np
var=np.array([[[6,7,8,9],[7,6,5,4],[8,7,6,5]]])
varsub=var-4
print(varsub)

[[[2 3 4 5]
  [3 2 1 0]
  [4 3 2 1]]]


### Numpy Multiply function

In [9]:
import numpy as np
a=np.array([7,3,4,5,1])
b=np.array([5,8,3,4,6,])
np.multiply(a,b)

array([35, 24, 12, 20,  6])

### 2D:

In [12]:
import numpy as np
var5=np.array([5,3,4,6])
var6=np.array([5,2,3,7])
varmul=np.multiply(var5,var6)
print(varmul)

[25  6 12 42]


### Numpy product function

In [14]:
a=np.array([4,8,6],float)
a.prod()

192.0

### numpy Divide Operator

In [16]:
import numpy as np
a=np.array([1,5,4,3,7])
b=np.array([7,6,5,4,3])
print(a/b)

[0.14285714 0.83333333 0.8        0.75       2.33333333]


### 2D:

In [19]:
import numpy as np
var7=np.array([5,6,7,5])
var8=np.array([2,2,2,2])
vardiv=np.divide(var7,var8)
print(vardiv)

[2.5 3.  3.5 2.5]


### 3D:

In [21]:
import numpy as np
var=np.array([[[6,7,8,9],[7,6,5,4],[8,7,6,5]]])
vardiv=var/2
print(vardiv)

[[[3.  3.5 4.  4.5]
  [3.5 3.  2.5 2. ]
  [4.  3.5 3.  2.5]]]


### Numpy Mod operator and Remainder function

### Numpy Reminder function

In [22]:
import numpy as np
a=np.array([1,5,4,3,7])
b=np.array([7,6,5,4,3])
np.remainder(a,b)

array([1, 5, 4, 3, 1])

### 1D:

In [1]:
import numpy as np
var=np.array([6,5,4,3])
varmod=var%2
print(varmod)

[0 1 0 1]


### 2D:

In [2]:
import numpy as np
var9=np.array([6,5,4,3])
var1=np.array([5,4,3,2])
varmod=np.mod(var9,var1)
print(varmod)

[1 1 1 1]


### 3D:

In [4]:
import numpy as np
var=np.array([[6,5,4,3],[4,8,7,5],[6,4,2,8]])
varmod=var%2
print(varmod)

[[0 1 0 1]
 [0 0 1 1]
 [0 0 0 0]]


### Numpy power function

In [1]:
import numpy as np
a=np.array([7,3,4,5,1])
b=np.array([3,4,5,6,7])
np.power(a,b)

array([  343,    81,  1024, 15625,     1])

### 3D:

In [2]:
import numpy as np
var=np.array([[[4,3,2,5],[4,2,3,5],[1,2,3,4]]])
varpower=var**2
print(varpower)

[[[16  9  4 25]
  [16  4  9 25]
  [ 1  4  9 16]]]


### Numpy Reciprocal function

In [3]:
import numpy as np
a=np.array([7,3,4,5,1])
np.reciprocal(a)

array([0, 0, 0, 0, 1])

## 2D:

In [4]:
import numpy as np
var5=np.array([1,5,4,3,7])
var4=np.array([2,3,4,5,1])
varreciprocal=np.reciprocal(var5)
print(varreciprocal)
varreciprocal=np.reciprocal(var4)
print(varreciprocal)

[1 0 0 0 0]
[0 0 0 0 1]


### 3D:

In [5]:
import numpy as np
var=np.array([[[42,32,22,25],[11,1,43,24],[19,28,37,66]]])
varreciprocal=np.reciprocal(var)
print(varreciprocal)

[[[0 0 0 0]
  [0 1 0 0]
  [0 0 0 0]]]
